### PR TITLE
JDF-782: Replace add-user instructions and fix links to point to JBoss developer shared repository

### PR DESCRIPTION
**Pull request by sgilda**
@rafabene : In addition to the link, can you please make sure the credentials specified are also correct?

### CODE REVIEW

**Comment by mareknovotny** [comment]
Do we need to push users to change admin's password to ours if they already have admin account setup? I don't know how is that admin account used in the quickstart though.

**Comment by sgilda** [comment]
@mareknovotny : I noted that this quickstart tests for 'admin' privileges in the quickstart 'CustomAuhtorizer.java' file, so  I added an admin user in the same way we do in the EAP quickstarts. It's not meant to replace an existing admin user. It's just meant to give them standard admin login to use for quickstarts. You are right that they do not need to change the admin username or password  to ours. Would an existing admin user have the username 'admin'? Would you like me to change the wording?

**Comment by mareknovotny** [comment]
probably, just imagine what will you do if admin user is already there. The command don't ask, just update the password of the existing admin account. Just saying ;-)

**Comment by sgilda** [comment]
@mareknovotny : Better?

**Comment by sgilda** [comment]
Reopened this pull with the correct JIRA number.

**Pull request closed without merging**
