### PR TITLE
WFK2-683 Fixed failing QUnit tests in contacts-mobile-basic

### PR DESCRIPTION
**Pull request by okiss**

### CODE REVIEW

**Comment by VineetReynolds** [comment]
+1. I thought I fixed this,

**Comment by VineetReynolds** [comment]
On second thoughts, I think this behaves differently in browsers that support HTML5 input validation.

**Comment by joshuawilson** [comment]
This fix is what it should be to put things back to the way they need to be.  There is a comment about it in the README that explains that these tests do not work in Chrome.

Please merge.

**Comment by okiss** [comment]
I removed the line with no change

**Comment by mareknovotny** [comment]
Merged.

**Pull request closed without merging**
