### PR TITLE
JDF-335 Modified project structure to Hybrid Mobile project.

### PR DESCRIPTION
**Pull request by VineetReynolds**
This quickstart now uses the Hybrid Mobile project structure in JBDS 7. The project can be imported into JBDS 7 as a Hybrid Mobile project and deployed to Android or iOS  devices or emulators.

Note - this forcibly adds an Eclipse project so that it can be shared among users and imported into JBDS 7.1 workspaces.

### CODE REVIEW

**Comment by VineetReynolds** [comment]
Please don't merge yet. The README lacks links to comprehensive documentation on how to install some dependencies like XCode and the iOS simulator, or ADT. It also lacks information on how to construct the hybrid mobile app from an existing web-app. I need some clarifications on whether this should be corrected before merging.

**Comment by VineetReynolds** [comment]
Specifically, the existing README refers http://aerogear.org/docs/guides/HTML5ToHybridWithCordova/ and http://aerogear.org/docs/guides/CordovaSetup/ and we may need more relevant docs for the Hybrid Mobile project in the updated README.

**Comment by VineetReynolds** [comment]
@sgilda The iOS simulator option is available only on a Mac. That's one of the reasons why the README and/or the docs referenced needs improvement/rewriting.

**Comment by sgilda** [comment]
I see! Maybe I'll wait to test AFTER the README is updated for all users. :-)

**Comment by sgilda** [comment]
Turns out, I didn't follow the instructions under "System Requirements". I'll try it all again from scratch.

**Comment by sgilda** [comment]
It might be useful to add a separate "Prerequisites" section. Or, the other option is to add a step 1 to the "Deploy and Access the application" section 
1. Be sure you installed JBoss Mobile tools as described above, (or something like that)

**Comment by sgilda** [comment]
I tried this again. First, I followed the instructions in the first link (http://developer.android.com/tools/sdk/eclipse-adt.html) to install the ADT plugin, but ran into a lot of issues. First I was missing the 'SDK Platform Android', then I had a lot of problems with missing Android SDK Platform Tools and later with wrong versions of the tools. It said I needto update from 16.0.2 to 22.2.1, but it only upgraded me to 22.0.0 and I had to do the process twice. 

After all that, I noticed this in the README: "If you need more detailed instructions to setup JBDS 7 with JBoss Hybrid Mobile Tools + CordovaSim, you can take a look at the user guide" and it takes you to https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/7.1/html/User_Guide/Install_Hybrid_Mobile_Tools_and_CordovaSim.html where you can drag the link to JBoss Central. That seemed to be much easier. I wonder if that information should be listed first.

I was finally able to Run as --> Run on Android Simulator. 
The simulator appears, but I don't see anything other than the  Date, charging percentage, and lock symbol. I wasn't sure what to do at this point.

I'm not very familiar with the Android simulator, but it seemed familiar so I searched old chat and found that you need to click on the `MENU` button. Will developers know to click that button? I assume so but am not sure.

I was able to add a member and to list members.

**Comment by sgilda** [comment]
@VineetReynolds : For the `Kitchensink Apache Cordova iOS Example` system requirements, do you need to install Hybrid Mobile Tools and CordovaSim? That install seems to be for Android.

If you do need to install it, I wonder if it would be simpler to have 1 common instruction set up trhough "Import the Quickstart Code" and give separate instructions when you get to the deployment?

**Comment by VineetReynolds** [comment]
@sglida Yes the tools need to be installed on a Mac-based JBDS installation as well.

**Comment by VineetReynolds** [comment]
@sgilda The emulators used could be have different user interfaces (every Android version may have it's own user interface). I don't think we should address how to launch the app, since the tooling launches the app in the background. The core issue to address would be whether to unlock the 'phone' before seeing the running app.

**Comment by sgilda** [comment]
@VineetReynolds : I made some minor changes to the README to move the SDK and JDBS plug-in installs to a separate section so they're more obvious. I also added instructions to unlock the emulator. I submitted a pull back to you. Feel free to take what you want, if anything, from it.

**Comment by sgilda** [comment]
@VineetReynolds : Where does this quickstart pull stand?  Please let me know if this one is ready to merge.

**Pull request closed without merging**
