### PR TITLE
JDF-643 and JDF-644

### PR DESCRIPTION
**Pull request by VineetReynolds**
Fixed issue in iOS where displayNames are null.

Fixed text formatting issues involving display of ellipses in headers and buttons in footers.

### CODE REVIEW

**Comment by sgilda** [comment]
@VineetReynolds : I can only test the Android emulator, but I have a question that is probably not related to this change, but I'm curious. 
- I click on`List Members`.
- I click on the JSON link for one of the members to see the JSON response.
- When I click the `Back` button, it takes me to the home page instead of the Member list page that originated this request. 
  Is that the expected behavior?

**Comment by VineetReynolds** [comment]
@sgilda No it is not expected behavior, but from what I've seen thus far, it is due to either the StatusBar plugin (which works on iOS only), the Hybrid Mobile tooling in JBDS or Cordova itself. This is not something that can be fixed in the quickstart as far as I know.

**Comment by VineetReynolds** [comment]
@sgilda I suspect JBDS for now, since at runtime, the app is forced to load statusbar.js in Android (through the tooling), even though it shouldn't. If this is confirmed, it will simply be treated as a known issue and it shouldnt affect whether the changes are merged.

**Comment by sgilda** [comment]
@VineetReynolds : Thanks for the answers! I will go ahead an merge. :-)

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
