### PR TITLE
JDF-787: Modify README metadata to optimize for Google search

### PR DESCRIPTION
**Pull request by sgilda**
Please review carefully for typos and valid descriptions. :-)

### CODE REVIEW

**Comment by joshuawilson** [comment]
@sgilda can you please update the contacts QS to:

contacts-mobile-basic: Basic CRUD Example Using HTML5, jQuery Mobile and JAX-RS

**Comment by sgilda** [comment]
@joshuawilson : The portion after the 'quickstart-title: ' has to be 55 characters or less. Your text above hass 57 characters. How about:

contacts-mobile-basic: Basic CRUD Using HTML5, jQuery Mobile and JAX-RS 
or
contacts-mobile-basic: CRUD Example Using HTML5, jQuery Mobile and JAX-RS
or
contacts-mobile-basic: CRUD Contacts Using HTML5, jQuery Mobile and JAX-RS

**Comment by sgilda** [comment]
Do not merge. I have found some typos and am making some fixes.

**Comment by sgilda** [comment]
@joshuawilson : I opted for: 

```
    contacts-mobile-basic: CRUD Example Using HTML5, jQuery Mobile and JAX-RS
```

Let me know if you prefer something else.

This is ready for review.

**Comment by joshuawilson** [comment]
I like:

contacts-mobile-basic: CRUD Example Using HTML5, jQuery Mobile and JAX-RS

**Comment by sgilda** [comment]
Is this okay to merge now or does someone want to review the changes?

**Comment by sgilda** [comment]
@mareknovotny reviewed and okayed the merge.

**Pull request merged**
