### PR TITLE
[JDF-687] - Refactor contact-mobile-basic.

### PR DESCRIPTION
**Pull request by joshuawilson**
Change the package structure from 'package by layer' to 'package by feature'.
Please refer to http://www.javapractices.com/topic/TopicAction.do?Id=205 for an explanation. 

Combine Repository and Registration into DAO. The CRUD methods were broken up and so this combines them.  Also the Repository should be a DAO based on Martin Fowlers explanation in "Patterns of Enterprise Application Architecture".  Here is a quote from the book, "A Repository mediates between the domain and data mapping layers, acting like an in-memory domain object collection."

Replace references to Member with Contact. This quickstart was based on the HTML5 Archetype and so it started with 'members' but to give it a clean feel I changed it to 'contacts'.

### CODE REVIEW

**Comment by joshuawilson** [comment]
@pmuir I know you are big time and have a ton going on but I would really appreciate it if you could take a minute to look at the structure in this quickstart.  I have refactored several things, but the biggest is the 'package by feature, not by layer' that we talked about.  If this looks good to you, I would like to apply it to the other quickstarts.

**Comment by joshuawilson** [comment]
@VineetReynolds if you have some time, can you please look at this too.

**Comment by sgilda** [comment]
@joshuawilson :
I successfully built and deployed the quickstart.
I accessed the application at http://localhost:8080/jboss-contacts-mobile-basic
I clicked on the menu pullout and chose `Add contact`
I entered data and clicked `Save`.
I get this error:
JBAS014356: Not a business method org.jboss.quickstarts.wfk.contact.Contact org.jboss.quickstarts.wfk.contact.ContactDAO.findByEmail(java.lang.String). Do not call non-public methods on EJB's

**Comment by pmuir** [comment]
@joshuawilson FWIW, I agree on packaging by feature, not layer.

**Comment by sgilda** [comment]
This pull was closed due to branch rename. It was later replaced by this pull: https://github.com/jboss-developer/jboss-wfk-quickstarts/pull/150

**Pull request closed without merging**
