### PR TITLE
Removed most QSTools Violations

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by sgilda** [comment]
Are the files in the guide/ directory being removed because they'll only be in one location? 

I wonder if we need a place to store common files used by all the quickstarts in all products>

**Comment by sgilda** [comment]
This builds successfully. Other than the few minor comments above, this looks good to me.

**Comment by rafabene** [comment]
The versions was fixed on commit https://github.com/rafabene/jboss-wfk-quickstarts/commit/bfc1f54be8381199189d26d3e1388c25b6fe7172

Yes. I think that the guide/ should remain only on EAP or somewhere else as you suggest.

**Comment by sgilda** [comment]
I'm a little concerned about removing the guide information until we can point them to information, but we can deal with that later. 

Looks good to me then.

**Comment by rafabene** [comment]
MErged

**Pull request closed without merging**
