### PR TITLE
JDF-640 Updated functional tests

### PR DESCRIPTION
**Pull request by okiss**
Updated tests including kitchensink-angularjs and kitchensink-backbone tests (JDF-640) and added functional tests for contacts-mobile-basic quickstart.

### CODE REVIEW

**Comment by sgilda** [comment]
I started testing with the contacts-mobile-basic quickstarts. I copied the instructions in section "Run the Arquillian Functional Tests"  from the `deltaspike-authorization` quickstart:
1. I started the JBoss EAP server.
2. I ran `mvn clean package`
3. I navigated to the functional-tests directory and ran: `mvn clean verify -Parq-jbossas-remote`

I see a lot of blank browsers pop up, but I see errors in the console log. This is the result:
Tests in error: 
  requiredFieldsValidationTest(org.jboss.as.quickstarts.contacts.test.ContactsMobileBasicTest): java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(Capabilities): org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
  contactFormValidationTest(org.jboss.as.quickstarts.contacts.test.ContactsMobileBasicTest): java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(Capabilities): org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
  addContactTest(org.jboss.as.quickstarts.contacts.test.ContactsMobileBasicTest): java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(Capabilities): org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
  duplicateEmailValidationTest(org.jboss.as.quickstarts.contacts.test.ContactsMobileBasicTest): java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(Capabilities): org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
  editContactTest(org.jboss.as.quickstarts.contacts.test.ContactsMobileBasicTest): java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(Capabilities): org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
  org.jboss.as.quickstarts.contacts.test.ContactsMobileBasicTest: Unexpected callable present in Drone Context, should be already instantiated at this moment.

Tests run: 9, Failures: 0, Errors: 6, Skipped: 0

**Comment by sgilda** [comment]
Tested the following and they were successful:
- deltaspike-authorization : OK
- deltaspike-beanmanagerprovider : OK
- deltaspike-exception-handling : OK
- deltaspike-helloworld-jms: OK
- deltaspike-projectstage : OK
- helloworld-errai  : OK
- helloworld-gwt : OK
- helloworld-html5 : OK
- helloworld-rf : OK
- kitchensink-angularjs-bootstrap : OK
- kitchensink-angularjs : OK
- kitchensink-backbone : OK
- kitchensink-deltaspike : OK
- kitchensink-rf : OK
- richfaces-validation : OK
- spring-greeter : OK
- spring-kitchensink-asyncrequestmapping : OK
- spring-kitchensink-basic : OK
- spring-kitchensink-controlleradvice : OK
- spring-kitchensink-matrixvariables : OK
- spring-kitchensink-springmvctest : OK
- spring-petclinic : OK (runs tests 3 times)

Will try contact-mobile-basic tests again.

**Comment by sgilda** [comment]
I tried the contact-mobile-basic again with the same results. Here's some more information:
- My default browser is Chrome.
- I see 5 instances of Firefox browser instances open that remain blank with no URL pasted in the address.
- I also see numerous errors like the following: 
  
    JavaScript error: chrome://browser/content/urlbarBindings.xml, line 654: aUrl is undefined

**Comment by sgilda** [comment]
@okiss : I updated the contact-mobile-basic quickstart README file with instructions to run the functional tests and issued this pull back to you: https://github.com/okiss/jboss-wfk-quickstarts/pull/1

**Comment by okiss** [comment]
I used incorrect version of WFK BOM in the pom.xml so the test was using an older version of Selenium, incompatible with newer Firefox. I updated the version and the test should work now.

**Comment by maschmid** [comment]
The updated version works for me. The PR is good to be merged from my POV.

**Comment by sgilda** [comment]
Squashed and merged.

**Comment by sgilda** [comment]
Merged to 2.5.x instead of 2.5.x-develop

**Comment by sgilda** [comment]
Merged to 2.5.x-develop

**Pull request closed without merging**
