### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by LightGuard**
Correcting the fork link for DEVELOPER-410

### CODE REVIEW

**Comment by sgilda** [comment]
Looks good. Would you like me to merge this now?

**Comment by LightGuard** [comment]
I don't see why not. Thanks

On Thu, May 15, 2014 at 11:21 AM, sgilda notifications@github.com wrote:

> Looks good. Would you like me to merge this now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jboss-developer/jboss-wfk-quickstarts/pull/160#issuecomment-43239009
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by mareknovotny** [comment]
we should merge to 2.6.x branch too if that is bug fixing, just to not lose that.

**Comment by sgilda** [comment]
I was told by someone that I don't need to merge any changes to 2.6.x yet, so I haven't been doing that. Should I go back through all the commits and merge them?

**Comment by sgilda** [comment]
Actually, there was no 2.6.x branch at that time. Was it created recently?

**Comment by sgilda** [comment]
Done.

**Comment by mareknovotny** [comment]
@sgilda yes, there is 2.6.x branch from yesterday WFK went to ER1, so this is important to not  diverge much

**Comment by sgilda** [comment]
@mareknovotny : You need to let me know these things. I had no clue it was created. ;-)

I merged it!

**Pull request merged**
