### PR TITLE
Added functional tests for Petclinic-spring quickstart

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by pmuir** [comment]
@joshuawilson could you review this one, and make sure the tests work please?

**Comment by joshuawilson** [comment]
@pmuir yes I can look at them tonight or tomorrow.

**Comment by joshuawilson** [comment]
Actually I would prefer that any changes done to Petclinic that are not absolutely needed to get it to run on JBoss be submitted to the Spring source.  It is very important that we don't start to maintain another branch.  If @MatousJobanek is unwilling or doesn't have the time, then I will be more then happy to submit a PR with Spring.

I'll still review change.

**Comment by sgilda** [comment]
I ran the functional tests and they work, however, I get this warning at the end:

[WARNING] The requested profile "arq-jbossas-remote" could not be activated because it does not exist.

Is that to be expected?

**Comment by MatousJobanek** [comment]
Hi,

thank you for the code review. 
I have added the proposed NOTE into the README file.

As regards the WARNING - @sgilda are you sure, that you ran the functional tests from the "functional-tests/" directory (as written in the README file)? In the "functional-tests/pom.xml" file is the profile "arq-jbossas-remote" present, so the warning is weird, especially when the tests ran successfully.

**Comment by MatousJobanek** [comment]
@joshuawilson there is no change in the Petclinic project itself, I had added only the directory with functional tests and changed the README file to let user know how the tests run. Do you still insist on submitting these changes to the Spring source?

**Comment by pmuir** [comment]
IMO, it's reasonable to add this one directory to the example. However, we could also put it as a separate top level directory as an exception to the rule, with the goal of keeping it as aligned to Spring as possible. @maschmid, @burrsutter, @rdruss wdyt?

**Comment by maschmid** [comment]
The functional test is just an additional directory, it doesn't modify the original quickstart in any way. I don't care too much where exactly the functional tests be. From our point of view it would even be easier to have them completely separate in a single functional-tests/ so that they could share code.

**Comment by sgilda** [comment]
@MatousJobanek : You are correct. I did not follow the instructions. It's all good. :-)

**Comment by joshuawilson** [comment]
@MatousJobanek I will not insist on submitting the changes to Spring at this time.

Also, I ran the tests from the functional-tests dir and it gave me errors right away about not being able to get to the Maven repo to download the libs needed.  However when I went to the root of the quickstart the tests ran with only the warning that @sgilda found.

**Comment by joshuawilson** [comment]
@MatousJobanek - I checked and it looks like running the tests from the root only runs the existing unit tests not your functional tests.  So here is the error that I get when I run it following your directions.

<pre><code>
$ mvn clean verify -Parq-jbossas-remote
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jboss.as.quickstarts.wfk:jboss-petclinic-spring-test-webdriver:2.4.0-redhat-SNAPSHOT (c:\Users\Joshua\git\jobanek\jboss-wfk-quickstarts\petclinic-spring\functional-tests\pom.
xml) has 5 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.wfk:jboss-javaee-6.0-with-tools:pom:2.4.0-redhat-1 in http://jboss-developer.github.io/temp-maven-repo/ was cached in the local rep
ository, resolution will not be reattempted until the update interval of jboss-developer-repository has elapsed or updates are forced @ line 61, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.graphene:graphene-webdriver:pom is missing. @ line 72, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 79, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 85, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.as:jboss-as-arquillian-container-remote:jar is missing. @ line 115, column 29
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
</code></pre>

**Comment by joshuawilson** [comment]
@MatousJobanek - looks the wfk BOM had the wrong version 

you had:
    `<version.jboss.bom.wfk>2.4.0-redhat-1</version.jboss.bom.wfk>`

and I changed it to:
    `<version.jboss.bom.wfk>2.4.0-build-5</version.jboss.bom.wfk>`

I don't know what is the correct version but this one worked.

It succeeded, so that is good.
There were a few warnings that you may want to look into.
`WARNING: Deprecated Enhancer type, please implement DroneInstanceEnhancer instead. Enhancing WebDriver @Default using enhancer org.jboss.arquillian.graphene.integration.GrapheneEnhancer with precedence -100`

`[WARNING] JAR will be empty - no content was marked for inclusion!`

**Comment by joshuawilson** [comment]
@MatousJobanek - The classes need the licensing applied.

**Comment by MatousJobanek** [comment]
@joshuawilson thank you for the reminder of the version and licensing - I set the version in our WFK test suite and I totally forgot to change it.
version changed, licensing added

The first WARNING - this is minor "problem" in Drone - it uses deprecated functionality of Arquillian, but it doesn't have any affect on the results

The second WARNING - there is no need to package anything in the JAR - it is only test

**Comment by pmuir** [comment]
I see a number of errors running the tests:

```
Running org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest
Oct 10, 2013 5:31:41 PM org.jboss.arquillian.drone.webdriver.factory.remote.reusable.ReusedSessionPernamentFileStorage readStore
INFO: Reused session store is not available at /Users/pmuir/.drone-webdriver-session-store, a new one will be created.
Oct 10, 2013 5:32:09 PM org.jboss.arquillian.drone.impl.DroneEnhancer enhanceDrone
WARNING: Deprecated Enhancer type, please implement DroneInstanceEnhancer instead. Enhancing WebDriver @Default using enhancer org.jboss.arquillian.graphene.integration.GrapheneEnhancer with precedence -100
Oct 10, 2013 5:32:25 PM org.jboss.arquillian.drone.impl.DroneEnhancer deenhanceDrone
WARNING: Deprecated Enhancer type, please implement DroneInstanceEnhancer instead. Deenhancing WebDriver @Default using enhancer org.jboss.arquillian.graphene.integration.GrapheneEnhancer with precedence -100
Tests run: 8, Failures: 1, Errors: 7, Skipped: 0, Time elapsed: 46.86 sec <<< FAILURE!

Results :

Failed tests:   editPet(org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest): There are two pet which can be edited. expected:<2> but was:<0>

Tests in error: 
  findOwner(org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest): Timed out after 5 seconds: Waiting for owner search link
  addVisit(org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest): Cannot locate element using: table:contains('Samantha') a:contains('Add Visit')
  addOwner(org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest): Timed out after 5 seconds: Waiting for owner search link
  addPet(org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest): Cannot locate element using: a:contains('Add New Pet')
  findVet(org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest): Cannot locate element using: a:contains('Veterinarians')
  checkXmlAndFeedOfVets(org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest): Cannot locate element using: a:contains('Veterinarians')
  throwException(org.jboss.as.quickstarts.spring.petclinic.test.webdriver.PetclinicTest): Cannot locate element using: a:contains('Error')
```

**Comment by pmuir** [comment]
Running again, it's all good.

**Comment by pmuir** [comment]
Merged

**Pull request closed without merging**
