### PR TITLE
README update. Spring 3.2 version replaced with 4.0

### PR DESCRIPTION
**Pull request by ecervena**
README update. Spring 3.2 version replaced with 4.0

### CODE REVIEW

**Comment by joshuawilson** [comment]
I am unsure if this is a good change or not. These features were added in Spring 3.2, though they still exist in 4.0, the reason for the quickstart is demonstrate their use. By changing the wording you imply that it is demonstrating a 4.0 version of the feature.  I would like @sgilda to weigh in on this.

**Comment by ecervena** [comment]
What about adding "introduced in Spring 3.2" wording? That should be clear enough.

**Comment by joshuawilson** [comment]
Thanks. That would work.

**Comment by mareknovotny** [comment]
Merged

**Pull request closed without merging**
