### PR TITLE
https://issues.jboss.org/browse/JDF-611 removed jboss-javaee-6.0 BOM

### PR DESCRIPTION
**Pull request by mareknovotny**
Some cleanup for better undertanding

### CODE REVIEW

**Comment by maschmid** [comment]
https://github.com/jboss-developer/jboss-wfk-quickstarts/blob/2.5.x-develop/pom.xml#L60 :

&lt;version.jboss.spec.javaee.6.0>3.0.2.Final-redhat-4&lt;/version.jboss.spec.javaee.6.0>  

 should probably be removed as well

**Comment by mareknovotny** [comment]
yes, it seems not used anywhere. I will send an update

**Comment by rafabene** [comment]
The changes on helloworld-rf should be made on https://github.com/richfaces/jdf-quickstarts first otherwise it can get lost on next richfaces synch

**Comment by mareknovotny** [comment]
the issue I recall is that Richfaces team doesn't want to use WFK BOMs or has that changed?

**Comment by rafabene** [comment]
Yes. They don't use WFK Boms. They're migrated using qstools and this config file: https://github.com/jboss-developer/maven-qstools-plugin/blob/master/config/qstools_config.yaml#L197

**Comment by mareknovotny** [comment]
so isn't that migration wrong. it should replace all org.jboss.spec:jboss-javaee-6.0 into org.jboss.bom.wfk:\* boms.

**Comment by mareknovotny** [comment]
Look here https://github.com/richfaces/jdf-quickstarts/blob/master/helloworld-rf/pom.xml#L69 it should be migrated to org.jboss.bom.wfk:jboss-javaee-6.0-with-richfaces cleanly. So it doesn't rely on richfaces quickstarts repository. You need to merge this change and later fix the migration steps.

**Comment by rafabene** [comment]
PR merged https://github.com/jboss-developer/jboss-wfk-quickstarts/commit/6a9f26a5858e421d0b43ec763c5a1008632fd656

**Pull request closed without merging**
