### PR TITLE
WFK2-537: Unused imports removed from contacts-mobile-basic

### PR DESCRIPTION
**Pull request by ecervena**
Unused imports removed from contacts-mobile-basic.

### CODE REVIEW

**Comment by VineetReynolds** [comment]
I think this would be covered by #133.

**Comment by ecervena** [comment]
Agree

**Comment by sgilda** [comment]
@VineetReynolds said this should be closed after merging pull 133 as it contains the same fix.

**Comment by joshuawilson** [comment]
@sgilda, I confirmed that this PR is the same code that is in 133 and should be closed.

**Comment by sgilda** [comment]
I merged pull 133. Closing this one.

**Pull request closed without merging**
