### PR TITLE
adding graphene functional-tests to kitchensink-deltaspike

### PR DESCRIPTION
**Pull request by maschmid**
Adding the first functional test as a template for the other quickstarts' functional tests.

This commit depends on the Drone/Graphene upgrade in the WFK BOM (https://github.com/jboss-developer/jboss-wfk-boms/pull/3 )

### CODE REVIEW

**Comment by pmuir** [comment]
Looks good to me, once @sgilda has reviewed.

**Comment by sgilda** [comment]
Oops. No it doesn't. I'm getting failures when I run the tests. 

I started my server and see: 

```
    JBoss AS 7.1.1.Final "Brontes" started in 16842ms
```

It hangs a while on this:

```
    Running org.jboss.as.quickstarts.kitchensink.test.MemberRegistrationTest
```

Then I get:

```
    Tests in error: 
        org.jboss.as.quickstarts.kitchensink.test.MemberRegistrationTest: Cannot deploy: test.war
```

The surefire reports show this cause:

Caused by: java.net.ConnectException: JBAS012144: Could not connect to remote://127.0.0.1:9999. The connection timed out
    at org.jboss.as.protocol.ProtocolConnectionUtils.connectSync(ProtocolConnectionUtils.java:130)

**Comment by sgilda** [comment]
I'll start over with a clean server.

**Comment by sgilda** [comment]
I am still not able to run `mvn -U clean test -Parq-jbossas-remote` successfully.

It hangs at:  Running org.jboss.as.quickstarts.kitchensink.test.MemberRegistrationTest

When I hit CTRL-BREAK to stop it, the server seems to be in a bad state and I can't stop it. I can't even kill the process with 'kill -9 <process-id>'

**Comment by sgilda** [comment]
It hangs for the functional tests also: `mvn clean verify -Parq-jbossas-remote`.

**Comment by sgilda** [comment]
@maschmid : @rafabene confirmed that the Arquillian and functional tests no longer works on AS 7.1.1.Final. It does however work on EAP 6.1.

Rather than try to figure out what is broken in AS 7.1.1, I think we should just target this for EAP 6.1. I don't think this is a big issue because we have a few other quickstarts that require EAP 6.1.

Could you update the README file in a manner similar to this one: https://github.com/jboss-developer/jboss-eap-quickstarts/blob/master/ejb-security-interceptors/README.md

Under **System requirements** make sure it says: 
The application this project produces is designed to be run on JBoss Enterprise Application Platform 6.1.

Then add a  **Prerequisites** section like this:

## Prerequisites

_Note_: Unlike most of the quickstarts, this one requires JBoss Enterprise Application Platform 6.1 or later.

Then later, make sure you remove references to AS 7.1.1.

**Comment by maschmid** [comment]
This PR doesn't modify the integration tests. The functional tests hang on AS7.1.1 for the same reason. All the other quickstarts' arquillian tests have the same problem.

I propose we should handle the issue separately, as this issue is orthogonal to adding the functional tests. (I have opened https://issues.jboss.org/browse/JDF-501 to track the AS7.1.1 arquillian problem)

**Comment by sgilda** [comment]
Since we are targeting EAP 6.1 and later, the issue with AS 7.1 will go away. Merged.

**Pull request closed without merging**
